apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
    - port: 8761
      targetPort: 8761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      name: eureka-server-pod
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: vnsbear/eureka-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
